In [8]:
import os
import numpy as np
import pandas as pd

In [2]:
df_asym = pd.read_csv('../symmetry/symmetry_mean_ratings.csv')
df_asym['diff'] = df_asym.forward_rating - df_asym.backward_rating
df_asym['diff'] = df_asym['diff'].abs()
print(df_asym.shape)
df_asym.head()

(500, 12)

,relation1,relation2,comparison_type,pair1_word1,pair1_word2,pair2_word1,pair2_word2,forward_rating,forward_n,backward_rating,backward_n,diff
0,10a,10b,between-subtype,license,permission,yawn,boredom,3.76,50,3.740000,50,0.020000
1,8d,8e,between-subtype,breathe,live,athlete,medal,2.74,50,2.764706,51,0.024706
2,6e,6e,within-subtype,miser,splurge,miser,give,3.90,50,3.980000,50,0.080000
3,9h,9i,between-subtype,arrest,trial,foot,shoe,3.24,50,2.745098,51,0.494902
4,9a,9a,within-subtype,farm,tractor,bakery,cake,4.78,50,4.470588,51,0.309412

In [3]:
df_asym_top = df_asym[df_asym['diff'] > 0.1].copy()
print(df_asym_top.shape)
df_asym_top

(423, 12)

,relation1,relation2,comparison_type,pair1_word1,pair1_word2,pair2_word1,pair2_word2,forward_rating,forward_n,backward_rating,backward_n,diff
3,9h,9i,between-subtype,arrest,trial,foot,shoe,3.240000,50,2.745098,51,0.494902
4,9a,9a,within-subtype,farm,tractor,bakery,cake,4.780000,50,4.470588,51,0.309412
5,6h,6h,within-subtype,dress,naked,gild,plain,4.420000,50,4.800000,50,0.380000
6,9a,9b,between-subtype,abbey,nun,restaurant,food,4.860000,50,4.360000,50,0.500000
7,10d,10c,between-subtype,prescription,medication,documentary,event,3.760000,50,3.620000,50,0.140000
9,8d,8d,within-subtype,wash,clean,buy,own,5.840000,50,5.340000,50,0.500000
10,9b,9b,within-subtype,dairy,milk,mine,coal,5.300000,50,4.760000,50,0.540000
12,9f,3h,between-type,birthday,celebration,speed,movement,4.240000,50,4.880000,50,0.640000
14,10d,10d,within-subtype,pattern,dress,map,city,4.660000,50,5.020000,50,0.360000
15,4e,1a,between-type,perplexed,certain,rodent,mouse,1.580000,50,1.400000,50,0.180000
16,4b,4h,between-subtype,bright,dark,fracture,bone,1.882353,51,1.660000,50,0.222353
17,4g,4g,within-subtype,bright,dark,smiling,sad,5.420000,50,5.260000,50,0.160000
18,7c,7g,between-subtype,musician,instrument,wall,paint,3.254902,51,3.000000,50,0.254902
19,8f,8d,between-subtype,glue,adhesion,shoot,kill,4.600000,50,5.400000,50,0.800000
20,3c,4e,between-type,wet,saturated,tall,short,1.640000,50,2.000000,50,0.360000
21,10f,10f,within-subtype,hat,hair,wrapper,package,5.420000,50,4.900000,50,0.520000
22,1a,1a,within-subtype,vegetable,carrot,dog,chihuahua,6.540000,50,6.360000,50,0.180000
23,3g,3g,within-subtype,pen,pencil,father,mother,4.680000,50,4.340000,50,0.340000
26,4a,4a,within-subtype,noise,silence,abrasive,smooth,6.137255,51,6.240000,50,0.102745
27,8h,8h,within-subtype,sunscreen,burns,water,thirst,5.660000,50,4.705882,51,0.954118
29,5f,5f,within-subtype,round,roll,golden,gleam,4.660000,50,4.880000,50,0.220000
31,3d,3b,between-subtype,exaggerate,lie,ennui,boredom,4.160000,50,3.480000,50,0.680000
32,7e,7e,within-subtype,preach,disciple,perform,audience,5.420000,50,5.260000,50,0.160000
33,10e,10e,within-subtype,mathematics,numbers,anatomy,body,6.300000,50,5.840000,50,0.460000
34,4d,5g,between-type,forward,backward,sprint,fast,1.420000,50,1.660000,50,0.240000
35,3d,3h,between-subtype,hurt,kill,acceleration,speed,4.058824,51,3.840000,50,0.218824
37,8c,3c,between-type,water,shower,angry,enraged,2.882353,51,3.340000,50,0.457647
40,5d,5d,within-subtype,drunk,intoxication,pensive,thought,4.900000,50,4.720000,50,0.180000
41,7b,6h,between-type,salesperson,buyer,repair,damaged,3.400000,50,3.540000,50,0.140000
42,6h,6c,between-subtype,repair,damaged,destitution,abundance,3.140000,50,3.540000,50,0.400000
...,...,...,...,...,...,...,...,...,...,...,...,...
468,2b,2d,between-subtype,album,songs,church,preacher,4.320000,50,4.780000,50,0.460000
469,6g,6h,between-subtype,speed,slowly,wash,dirty,4.160000,50,3.480000,50,0.680000
470,3h,3h,within-subtype,rise,tide,flood,water,4.860000,50,3.647059,51,1.212941
471,2c,2c,within-subtype,quarter,pennies,poem,verses,4.800000,50,3.880000,50,0.920000
472,3a,3c,between-subtype,house,home,hunger,starvation,4.920000,50,3.860000,50,1.060000
473,2e,9f,between-type,therapy,talking,spring,breeze,3.380000,50,4.215686,51,0.835686
474,10d,1d,between-type,map,journey,cutlery,forks,2.260000,50,2.100000,50,0.160000
475,1b,1b,within-subtype,garment,skirt,artwork,sculpture,6.540000,50,6.000000,50,0.540000
476,4f,4h,between-subtype,rage,happiness,fracture,bone,1.840000,50,1.431373,51,0.408627
477,4e,4e,within-subtype,lazy,productive,mobile,inert,5.160000,50,4.820000,50,0.340000
478,8a,8a,within-subtype,germs,sickness,loss,grief,5.620000,50,5.500000,50,0.120000
479,5g,5i,between-subtype,withdrawal,timid,eat,satisfaction,3.360000,50,2.420000,50,0.940000
480,2g,2j,between-subtype,cocktail,alcohol,butterfly,cocoon,3.764706,51,3.660000,50,0.104706
481,8c,8a,between-subtype,water,shower,exercise,fitness,4.300000,50,3.900000,50,0.400000
482,4h,4h,within-subtype,deafness,hearing,gap,teeth,2.540000,50,3.620000,50,1.080000
484,1b,5e,between-type,clothing,shirt,sun,shine,2.140000,50,3.060000,50,0.920000
485,9i,9d,between-subtype,hands,gloves,war,weapon,3.260000,50,4.080000,50,0.820000
486,6a,6d,between-subtype,careful,reckless,plump,thinness,5.780000,50,5.560000,50,0.220000
487,7d,4f,between-type,donate,charity,rage,happiness,1.340000,50,1.200000,50,0.140000
488,4a,4h,between-subtype,cold,warm,infertility,reproduction,5.760000,50,4.803922,51,0.956078
489,6c,6c,within-subtype,dirt,cleanliness,sage,ignorance,4.509804,51,5.060000,50,0.550196
491,2d,2b,between-subtype,graduation,students,library,books,4.780000,50,5.260000,50,0.480000
492,7c,9h,between-type,shooter,gun,step,journey,3.160000,50,2.140000,50,1.020000
493,10a,10a,within-subtype,crown,sovereignty,wrinkle,age,4.720000,50,4.120000,50,0.600000
494,6h,6a,between-subtype,fill,empty,object,intangible,3.520000,50,3.700000,50,0.180000
495,9h,1a,between-type,narrative,epilogue,animal,pig,2.800000,50,3.840000,50,1.040000
496,2a,2b,between-subtype,bird,wings,pack,wolf,2.940000,50,2.080000,50,0.860000
497,7h,7h,within-subtype,conductor,baton,queen,throne,4.880000,50,4.700000,50,0.180000
498,1e,1c,between-subtype,lake,Erie,fish,trout,5.686275,51,6.137255,51,0.450980
499,4h,4h,within-subtype,pimple,skin,gap,teeth,5.235294,51,5.740000,50,0.504706

In [5]:
df_raw = pd.read_csv('relsim_raw_data.csv')
print(df_raw[(df_raw.pair_left_word1=='dull')&(df_raw.pair_left_word2=='bright')].sim_rating.mean())
print(df_raw[(df_raw.pair_right_word1=='dull')&(df_raw.pair_right_word2=='bright')].sim_rating.mean())

4.591549295774648
4.580246913580247

In [6]:
# lw1, lw2 = 'hairdresser', 'comb'
# rw1, rw2 = 'pitcher', 'baseball'
lw1, lw2 = 'mother', 'children'
rw1, rw2 = 'words', 'letters'

oneway = (df_raw.pair_left_word1==lw1)&(df_raw.pair_left_word2==lw2)&(df_raw.pair_right_word1==rw1)&(df_raw.pair_right_word2==rw2)
another = (df_raw.pair_right_word1==rw1)&(df_raw.pair_right_word2==rw2)&(df_raw.pair_left_word1==lw1)&(df_raw.pair_left_word2==lw2)

print(df_raw[oneway].sim_rating)
print(df_raw[oneway].sim_rating.mean())
print(df_raw[another].sim_rating.mean())

Series([], Name: sim_rating, dtype: int64)
nan
nan

In [7]:
for row in df_asym_top.iterrows():
    lw1 = row[1]['pair1_word1']
    lw2 = row[1]['pair1_word2']
    rw1 = row[1]['pair2_word1']
    rw2 = row[1]['pair2_word2']
    asym_diff = row[1]['diff']
    
    mask1 = ((df_raw.pair_left_word1==lw1) & 
             (df_raw.pair_left_word2==lw2) & 
             (df_raw.pair_right_word1==rw1) & 
             (df_raw.pair_right_word2==rw2))
    
    mask2 = ((df_raw.pair_left_word1==rw1) & 
             (df_raw.pair_left_word2==rw2) & 
             (df_raw.pair_right_word1==lw1) & 
             (df_raw.pair_right_word2==lw2))
    
    score1 = df_raw[mask1].sim_rating.mean()
    score1_n = df_raw[mask1].sim_rating.values.size
    score2 = df_raw[mask2].sim_rating.mean()
    score2_n = df_raw[mask2].sim_rating.values.size
    diff = score1-score2
    if not np.isnan(np.abs(diff)): 
        print(lw1, lw2, '     ', rw1, rw2)
        print(asym_diff, diff)#, score1_n, score2_n)

hairdresser comb       pitcher baseball
1.2599999999999998 0.0
dog tail       fish fin
0.20000000000000018 -0.583333333333333
raise elevate       house dwelling
0.27999999999999936 0.8809523809523814
wrinkle age       cross faith
1.4399999999999995 -1.875
make manufacture       run sprint
0.14509803922000053 0.5
sunburn painful       fire heat
0.14000000000000057 -1.166666666666667
pants trousers       boat ship
0.27843137255000006 -0.15584415584415634
tidy messy       solid liquid
0.13999999999999968 -0.4920634920634921
kitchen food       classroom students
0.11490196078000103 1.4285714285714288
germs sickness       loss grief
0.1200000000000001 0.9111111111111105