In [2]:
# Load the data

import pandas as pd
import numpy as np

all_data = pd.read_csv('transitivity_raw_data.csv')
all_data[:11]

,sub_num,trial_num,trial_type,wordA,wordB,wordC,wordD,rating,RT
0,1,1,real,nurse,patient,frog,tadpole,2,8579
1,1,2,real,veil,face,password,access,3,7959
2,1,3,real,brain,neuron,computer,chip,4,7005
3,1,4,real,dog,mailman,cat,mouse,4,4791
4,1,5,filler,mall,shops,widow,husband,1,3804
5,1,6,real,bird,feathers,cat,whiskers,6,5462
6,1,7,real,foot,shoe,wall,painting,5,8021
7,1,8,real,lawyer,books,chemist,beakers,4,7924
8,1,9,attention check,one,two,three,four,7,7686
9,1,10,real,snail,shell,rabbit,burrow,3,9103
10,1,11,real,wedding,bride,aquarium,fish,5,5284

In [3]:
# Find the "bad" subjects--those who failed too many attention checks

fail_threshold = 1
bad_subs = []
attn_checks = all_data[all_data['trial_type'] == 'attention check']
for sub_num in attn_checks['sub_num'].unique():
    sub_data = attn_checks[attn_checks['sub_num'] == sub_num]
    num_failed = 0
    good_analogy_rating = sub_data[sub_data['wordD'] == 'four']['rating'].iloc[0]
    bad_analogy_rating = sub_data[sub_data['wordD'] == 'zero']['rating'].iloc[0]
    if good_analogy_rating != 7:
        num_failed += 1
    if bad_analogy_rating != 1:
        num_failed += 1
    
    if num_failed >= fail_threshold:
        bad_subs.append(sub_num)
        
print 'Number of "bad" subjects:', len(bad_subs)

Number of "bad" subjects: 11

In [4]:
# Get the "good" data

good_rows = reduce(np.logical_and,
                   [all_data['sub_num'] != num for num in bad_subs])
good_data = all_data[good_rows]
print 'Number of "good" subjects:', len(good_data['sub_num'].unique())

real_trials = good_data[good_data['trial_type'] == 'real']
print 'Mean RT (seconds):', real_trials['RT'].mean() / 1000
print 'Mean overall rating:', real_trials['rating'].mean()

Number of "good" subjects: 60
Mean RT (seconds): 7.20855
Mean overall rating: 4.62083333333

In [5]:
# Creates a dictionary of all individual ratings for each analogy

from collections import defaultdict

def get_indiv_ratings_dict(data):
    ratings_dict = defaultdict(list)

    for r in xrange(data.shape[0]):
        row = data.iloc[r]
        wordA = row['wordA']
        wordB = row['wordB']
        wordC = row['wordC']
        wordD = row['wordD']
        rating = row['rating']

        analogy = (wordA, wordB, wordC, wordD)
        ratings_dict[analogy].append(rating)
    
    return ratings_dict

In [7]:
# Conduct separate ANOVA and Tukey HSD tests for each triad

import numpy as np
from scipy.stats import ttest_ind, f_oneway
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import math

real_ratings = get_indiv_ratings_dict(real_trials)

stimuli = [[['hat', 'head'], ['mask', 'face'], ['disguise', 'identity']],
           [['foot', 'shoe'], ['wrist', 'bracelet'], ['wall', 'painting']],
           [['dog', 'mailman'], ['cat', 'mouse'], ['horse', 'hay']],
           [['nurse', 'patient'], ['mother', 'baby'], ['frog', 'tadpole']],
           [['cocoon', 'butterfly'], ['egg', 'chicken'], ['wine', 'vineyard']],
           [['person', 'clothes'], ['bird', 'feathers'], ['cat', 'whiskers']],
           [['student', 'backpack'], ['snail', 'shell'], ['rabbit', 'burrow']],
           [['wedding', 'bride'], ['aquarium', 'fish'], ['carton', 'milk']],
           [['flock', 'bird'], ['hive', 'bee'], ['hangar', 'airplane']],
           [['lawyer', 'books'], ['chemist', 'beakers'], ['librarian', 'books']],
           [['veil', 'face'], ['password', 'access'], ['key', 'safe']],
           [['pride', 'lion'], ['brain', 'neuron'], ['computer', 'chip']]]

mean_ratings1 = []
mean_ratings2 = []
mean_ratings3 = []

for pair1, pair2, pair3 in stimuli:
    analogy1 = (pair1[0], pair1[1], pair2[0], pair2[1])
    analogy2 = (pair2[0], pair2[1], pair3[0], pair3[1])
    analogy3 = (pair1[0], pair1[1], pair3[0], pair3[1])
    
    ratings1 = real_ratings[analogy1]
    ratings2 = real_ratings[analogy2]
    ratings3 = real_ratings[analogy3]
    
    mean_rating1 = np.mean(ratings1)
    mean_rating2 = np.mean(ratings2)
    mean_rating3 = np.mean(ratings3)
    
    mean_ratings1.append(mean_rating1)
    mean_ratings2.append(mean_rating2)
    mean_ratings3.append(mean_rating3)
    
    # One-way ANOVA
    _, F_prob = f_oneway(ratings1, ratings2, ratings3)
    
    # Tukey's HSD test
    all_ratings = np.concatenate((ratings1, ratings2, ratings3))
    labels1 = np.repeat('1-2', len(ratings1))
    labels2 = np.repeat('2-3', len(ratings2))
    labels3 = np.repeat('1-3', len(ratings3))
    all_labels = np.concatenate((labels1, labels2, labels3))
    tukey_results = pairwise_tukeyhsd(all_ratings, all_labels)
    
    _, t_prob1 = ttest_ind(ratings1, ratings2)
    _, t_prob2 = ttest_ind(ratings1, ratings3)
    _, t_prob3 = ttest_ind(ratings2, ratings3)
    
    print '{}: mean rating = {}'.format(analogy1, mean_rating1)
    print '{}: mean rating = {}'.format(analogy2, mean_rating2)
    print '{}: mean rating = {}'.format(analogy3, mean_rating3)
    print
    print 't-test for 1-2 vs 2-3: p =', t_prob1
    print 't-test for 1-2 vs 1-3: p =', t_prob2
    print 't-test for 2-3 vs 1-3: p =', t_prob3
    print 'ANOVA for all groups: p =', F_prob
    print
    print tukey_results
    print
    print

('hat', 'head', 'mask', 'face'): mean rating = 6.65
('mask', 'face', 'disguise', 'identity'): mean rating = 5.65
('hat', 'head', 'disguise', 'identity'): mean rating = 3.2

t-test for 1-2 vs 2-3: p = 0.00514706093483
t-test for 1-2 vs 1-3: p = 2.14261901822e-10
t-test for 2-3 vs 1-3: p = 6.69162012739e-06
ANOVA for all groups: p = 3.1318244275e-11

Multiple Comparison of Means - Tukey HSD,FWER=0.05
=============================================
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
 1-2    1-3    -3.45   -4.4288 -2.4712  True
 1-2    2-3     -1.0   -1.9788 -0.0212  True
 1-3    2-3     2.45    1.4712  3.4288  True
---------------------------------------------


('foot', 'shoe', 'wrist', 'bracelet'): mean rating = 6.2
('wrist', 'bracelet', 'wall', 'painting'): mean rating = 5.75
('foot', 'shoe', 'wall', 'painting'): mean rating = 3.55

t-test for 1-2 vs 2-3: p = 0.146104996053
t-test for 1-2 vs 1-3: p = 2.24508570235e-06
t-test for 2-3 vs 1-3: p = 3.21186078559e-05
ANOVA for all groups: p = 6.2846515469e-08

Multiple Comparison of Means - Tukey HSD,FWER=0.05
=============================================
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
 1-2    1-3    -2.65   -3.6675 -1.6325  True
 1-2    2-3    -0.45   -1.4675  0.5675 False
 1-3    2-3     2.2     1.1825  3.2175  True
---------------------------------------------


('dog', 'mailman', 'cat', 'mouse'): mean rating = 5.5
('cat', 'mouse', 'horse', 'hay'): mean rating = 3.95
('dog', 'mailman', 'horse', 'hay'): mean rating = 2.3

t-test for 1-2 vs 2-3: p = 0.0147787697449
t-test for 1-2 vs 1-3: p = 3.72569605991e-06
t-test for 2-3 vs 1-3: p = 0.00356503068421
ANOVA for all groups: p = 4.63588090413e-06

Multiple Comparison of Means - Tukey HSD,FWER=0.05
=============================================
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
 1-2    1-3     -3.2   -4.5899 -1.8101  True
 1-2    2-3    -1.55   -2.9399 -0.1601  True
 1-3    2-3     1.65    0.2601  3.0399  True
---------------------------------------------


('nurse', 'patient', 'mother', 'baby'): mean rating = 5.55
('mother', 'baby', 'frog', 'tadpole'): mean rating = 6.35
('nurse', 'patient', 'frog', 'tadpole'): mean rating = 2.45

t-test for 1-2 vs 2-3: p = 0.0502872529055
t-test for 1-2 vs 1-3: p = 5.94246752819e-07
t-test for 2-3 vs 1-3: p = 1.21952932818e-10
ANOVA for all groups: p = 9.88978459393e-12

Multiple Comparison of Means - Tukey HSD,FWER=0.05
===========================================
group1 group2 meandiff lower  upper  reject
-------------------------------------------
 1-2    1-3     -3.1   -4.197 -2.003  True
 1-2    2-3     0.8    -0.297 1.897  False
 1-3    2-3     3.9    2.803  4.997   True
-------------------------------------------


('cocoon', 'butterfly', 'egg', 'chicken'): mean rating = 5.95
('egg', 'chicken', 'wine', 'vineyard'): mean rating = 4.9
('cocoon', 'butterfly', 'wine', 'vineyard'): mean rating = 3.05

t-test for 1-2 vs 2-3: p = 0.0858968559607
t-test for 1-2 vs 1-3: p = 1.16725781825e-06
t-test for 2-3 vs 1-3: p = 0.00779386755551
ANOVA for all groups: p = 3.30767793703e-05

Multiple Comparison of Means - Tukey HSD,FWER=0.05
=============================================
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
 1-2    1-3     -2.9   -4.3172 -1.4828  True
 1-2    2-3    -1.05   -2.4672  0.3672 False
 1-3    2-3     1.85    0.4328  3.2672  True
---------------------------------------------


('person', 'clothes', 'bird', 'feathers'): mean rating = 6.3
('bird', 'feathers', 'cat', 'whiskers'): mean rating = 5.35
('person', 'clothes', 'cat', 'whiskers'): mean rating = 3.35

t-test for 1-2 vs 2-3: p = 0.016740532771
t-test for 1-2 vs 1-3: p = 1.61454431272e-07
t-test for 2-3 vs 1-3: p = 0.000361611334603
ANOVA for all groups: p = 8.13183014863e-08

Multiple Comparison of Means - Tukey HSD,FWER=0.05
=============================================
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
 1-2    1-3    -2.95   -4.0416 -1.8584  True
 1-2    2-3    -0.95   -2.0416  0.1416 False
 1-3    2-3     2.0     0.9084  3.0916  True
---------------------------------------------


('student', 'backpack', 'snail', 'shell'): mean rating = 5.15
('snail', 'shell', 'rabbit', 'burrow'): mean rating = 4.95
('student', 'backpack', 'rabbit', 'burrow'): mean rating = 2.75

t-test for 1-2 vs 2-3: p = 0.716430547469
t-test for 1-2 vs 1-3: p = 6.32761916983e-05
t-test for 2-3 vs 1-3: p = 0.000451985088681
ANOVA for all groups: p = 5.65302520008e-05

Multiple Comparison of Means - Tukey HSD,FWER=0.05
=============================================
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
 1-2    1-3     -2.4   -3.7267 -1.0733  True
 1-2    2-3     -0.2   -1.5267  1.1267 False
 1-3    2-3     2.2     0.8733  3.5267  True
---------------------------------------------


('wedding', 'bride', 'aquarium', 'fish'): mean rating = 3.75
('aquarium', 'fish', 'carton', 'milk'): mean rating = 5.4
('wedding', 'bride', 'carton', 'milk'): mean rating = 3.7

t-test for 1-2 vs 2-3: p = 0.00321430918803
t-test for 1-2 vs 1-3: p = 0.926429122478
t-test for 2-3 vs 1-3: p = 0.00231962447653
ANOVA for all groups: p = 0.00239591442558

Multiple Comparison of Means - Tukey HSD,FWER=0.05
============================================
group1 group2 meandiff  lower  upper  reject
--------------------------------------------
 1-2    1-3    -0.05   -1.3199 1.2199 False
 1-2    2-3     1.65    0.3801 2.9199  True
 1-3    2-3     1.7     0.4301 2.9699  True
--------------------------------------------


('flock', 'bird', 'hive', 'bee'): mean rating = 6.35
('hive', 'bee', 'hangar', 'airplane'): mean rating = 5.75
('flock', 'bird', 'hangar', 'airplane'): mean rating = 3.35

t-test for 1-2 vs 2-3: p = 0.159060705891
t-test for 1-2 vs 1-3: p = 1.59504527925e-08
t-test for 2-3 vs 1-3: p = 6.32761916983e-05
ANOVA for all groups: p = 3.10813013861e-08

Multiple Comparison of Means - Tukey HSD,FWER=0.05
===========================================
group1 group2 meandiff lower  upper  reject
-------------------------------------------
 1-2    1-3     -3.0   -4.108 -1.892  True
 1-2    2-3     -0.6   -1.708 0.508  False
 1-3    2-3     2.4    1.292  3.508   True
-------------------------------------------


('lawyer', 'books', 'chemist', 'beakers'): mean rating = 5.8
('chemist', 'beakers', 'librarian', 'books'): mean rating = 5.8
('lawyer', 'books', 'librarian', 'books'): mean rating = 2.65

t-test for 1-2 vs 2-3: p = 1.0
t-test for 1-2 vs 1-3: p = 2.38764871036e-07
t-test for 2-3 vs 1-3: p = 4.31896647034e-07
ANOVA for all groups: p = 5.25328449962e-09

Multiple Comparison of Means - Tukey HSD,FWER=0.05
=============================================
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
 1-2    1-3    -3.15   -4.3381 -1.9619  True
 1-2    2-3     0.0    -1.1881  1.1881 False
 1-3    2-3     3.15    1.9619  4.3381  True
---------------------------------------------


('veil', 'face', 'password', 'access'): mean rating = 3.9
('password', 'access', 'key', 'safe'): mean rating = 5.4
('veil', 'face', 'key', 'safe'): mean rating = 2.5

t-test for 1-2 vs 2-3: p = 0.0139225760317
t-test for 1-2 vs 1-3: p = 0.017556082941
t-test for 2-3 vs 1-3: p = 9.05501868088e-06
ANOVA for all groups: p = 2.35958456362e-05

Multiple Comparison of Means - Tukey HSD,FWER=0.05
=============================================
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
 1-2    1-3     -1.4   -2.7731 -0.0269  True
 1-2    2-3     1.5     0.1269  2.8731  True
 1-3    2-3     2.9     1.5269  4.2731  True
---------------------------------------------


('pride', 'lion', 'brain', 'neuron'): mean rating = 4.2
('brain', 'neuron', 'computer', 'chip'): mean rating = 5.95
('pride', 'lion', 'computer', 'chip'): mean rating = 3.0

t-test for 1-2 vs 2-3: p = 0.00103467109181
t-test for 1-2 vs 1-3: p = 0.0546663416589
t-test for 2-3 vs 1-3: p = 1.93081425964e-06
ANOVA for all groups: p = 6.14696846147e-06

Multiple Comparison of Means - Tukey HSD,FWER=0.05
==========================================
group1 group2 meandiff lower  upper reject
------------------------------------------
 1-2    1-3     -1.2   -2.507 0.107 False
 1-2    2-3     1.75   0.443  3.057  True
 1-3    2-3     2.95   1.643  4.257  True
------------------------------------------

In [8]:
# Conduct overall ANOVA and Tukey HSD tests for all triads

_, t_prob1 = ttest_ind(mean_ratings1, mean_ratings2)
_, t_prob2 = ttest_ind(mean_ratings1, mean_ratings3)
_, t_prob3 = ttest_ind(mean_ratings2, mean_ratings3)
print 'Overall:'
print
print 't-test for 1-2 vs 2-3: p =', t_prob1
print 't-test for 1-2 vs 1-3: p =', t_prob2
print 't-test for 2-3 vs 1-3: p =', t_prob3

f, prob = f_oneway(mean_ratings1, mean_ratings2, mean_ratings3)

all_ratings = np.concatenate((mean_ratings1, mean_ratings2, mean_ratings3))
labels1 = np.repeat('1-2', len(mean_ratings1))
labels2 = np.repeat('2-3', len(mean_ratings2))
labels3 = np.repeat('1-3', len(mean_ratings3))
all_labels = np.concatenate((labels1, labels2, labels3))
tukey_results = pairwise_tukeyhsd(all_ratings, all_labels)

print 'ANOVA for all groups: F = {}, p = {}'.format(f, prob)
print
print tukey_results

Overall:

t-test for 1-2 vs 2-3: p = 0.980552953734
t-test for 1-2 vs 1-3: p = 9.55490079787e-08
t-test for 2-3 vs 1-3: p = 2.06309110805e-10
ANOVA for all groups: F = 45.5720687796, p = 3.20403645028e-10

Multiple Comparison of Means - Tukey HSD,FWER=0.05
=============================================
group1 group2 meandiff  lower   upper  reject
---------------------------------------------
 1-2    1-3   -2.4542  -3.1812 -1.7272  True
 1-2    2-3   -0.0083  -0.7353  0.7187 False
 1-3    2-3    2.4458   1.7188  3.1728  True
---------------------------------------------